/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "product.show": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "product.store": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "product.random": [],
    "category.top": [],
    "product.offers": [],
    "cart.add": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "cart.index": [],
    "cartItem.index": [],
    "cartItem.create": [],
    "cartItem.store": [],
    "cartItem.show": [
        {
            "name": "cartItem",
            "required": true,
            "binding": "id"
        }
    ],
    "cartItem.edit": [
        {
            "name": "cartItem",
            "required": true,
            "binding": "id"
        }
    ],
    "cartItem.update": [
        {
            "name": "cartItem",
            "required": true,
            "binding": "id"
        }
    ],
    "cartItem.destroy": [
        {
            "name": "cartItem",
            "required": true,
            "binding": "id"
        }
    ],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
